### ISSUE TITLE
poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [lukassindo/Song-Repository#1]
1. nazwy katalogow tworz malymi literami
2. tych katalogow `Sass` oraz `.sass-cache` nie powinno byc w repo, usun je, zakomituj zmiane i dodaj plik `.gitignore` wraz z zapisem zeby ignorowal zmiany w katalogu `.sass-cache`. Rowniez zakomituj i wypushuj na githuba. Jesli beda problemy z ignorowaniem tego katalogu, to zerknij tutaj: https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore
3. popraw wciecia w `style.scss`

**Comment by lukassindo** [comment]
Chyba trochę nie łapię. Chodzi o usunięcie katalogu sass w lokalnym repo na moim dysku? Wtedy nie będę miał pliku style.scss więc nie będę mógł pracować. Czy o usunięcię z githuba tych katalogów?

**Comment by michal-bootcamp** [comment]
do usuniecia sa te dwa katalogi: https://scr.hu/4Wg00L

swoj plik sass masz w folderze `sass` (z malej)

**Comment by michal-bootcamp** [comment]
w terminalu mozesz wyswietlic liste plkow w katalogu wraz z ukrytymi plikami/katalogami przez
`ls -al`

**Comment by lukassindo** [comment]
Przesyłam repo:

https://github.com/lukassindo/Song-Repository.git

Cały czas nie wiem jak zaktualizować w github kwestie nazwy katalogu css (a
dokładnie tego, żeby był z malej litery). Na repo zdalnym zmieniłem już
wszystkie katalogi na małoliterowe zrobiłem git add i commita, ale w github
nadal ten jeden się nie zmienia.
A jak się chce cały katalog wrzucić do indexi i skomitować to wystarczy
nazwę katalogu po git add wstawić?

Dzięki za info.


2017-12-17 16:50 GMT+01:00 michal-bootcamp <notifications@github.com>:

**Comment by michal-bootcamp** [comment]
jesli chodzi o zmiane wielkosci liter w nazwie folderu, to faktycznie pod windowsem moze byc to troche skomplikowane - dodaj mnie do repo jako kolaboratora (settings -> collaborators)

tak wystarczy nazwa katalogu po git add, mozesz tez dodawac wszystko przez `git add -A`

jak wysylasz na githubie zmiany gotowe do sprawdzenia, to wysylaj tez w panelu kodilli, bo tutaj moze mi umknac

**Comment by michal-bootcamp** [comment]
dorzucilem poprawki, zaciagnij je sobie przez `git pull`
